"""Initial migration

Revision ID: 001_initial
Revises:
Create Date: 2026-05-17 17:19:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', postgresql.UUID(as_uuid=True),
                              nullable=False),
                    sa.Column('login', sa.String(length=255), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('password', sa.String(length=255),
                              nullable=False),
                    sa.Column('first_name', sa.String(length=50),
                              nullable=True),
                    sa.Column('last_name', sa.String(length=50),
                              nullable=True),
                    sa.Column('is_superuser', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('id'),
                    sa.UniqueConstraint('login')
                    )
    op.create_table('refresh_tokens',
                    sa.Column('id', postgresql.UUID(as_uuid=True),
                              nullable=False),
                    sa.Column('user_id', postgresql.UUID(as_uuid=True),
                              nullable=False),
                    sa.Column('token', sa.String(length=255), nullable=False),
                    sa.Column('expires_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('login_history',
                    sa.Column('id', postgresql.UUID(as_uuid=True),
                              nullable=False),
                    sa.Column('user_id', postgresql.UUID(as_uuid=True),
                              nullable=False),
                    sa.Column('ip_address', sa.String(length=255),
                              nullable=False),
                    sa.Column('user_agent', sa.String(length=255),
                              nullable=False),
                    sa.Column('time', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id')
                    )
    op.create_table('social_accounts',
                    sa.Column('id', postgresql.UUID(as_uuid=True),
                              nullable=False),
                    sa.Column('user_id', postgresql.UUID(as_uuid=True),
                              nullable=False),
                    sa.Column('provider', sa.String(length=50),
                              nullable=False),
                    sa.Column('provider_user_id', sa.String(length=255),
                              nullable=False),
                    sa.Column('provider_email', sa.String(length=255),
                              nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id'),
                    sa.UniqueConstraint('provider', 'provider_user_id',
                                        name='uq_provider_user')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_accounts')
    op.drop_table('login_history')
    op.drop_table('refresh_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###